# Generated by Django 5.1.3 on 2024-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_year_group_completedquiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquizquestion',
            name='marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedquizquestion',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
